### ISSUE TITLE
Support config dir

### ISSUE THREAD

**Issue by davidlukac** [dzervas/ansible-vector#22]
`vector` can be run with `--config-dir` option, which is suitable for more complex configurations. I'm atm doing

```
    - import_role:
        name: vector
      become: yes

    - name: "Make vector to load whole config folder"
      community.general.ini_file:
        path: "{{ vector_systemd_file }}"
        section: Service
        option: ExecStart
        value: "/usr/bin/vector --config-dif {{ vector_root }}"
        no_extra_spaces: yes
        mode: '0664'
        backup: true
      become: yes
      notify: restart vector
```

but it would be great to support this directly in the role.

Also I believe the role run might fail, if complex config references `inputs` from _other_ files. Only the main config file loading will fail, before change to `systemd` file is applied, because the role attempts to start the `vector` even though there are further changes (and `notify: restart vector`) down the line.

**Comment by davidlukac** [comment]
ok, so this ^ didn't work as expected. I found this issue addressing it https://github.com/vectordotdev/vector/issues/7256 (released here https://vector.dev/releases/0.15.2/), not well documented though. I guess the solution then would be something like
```
- name: Set vector configs path
  ansible.builtin.lineinfile:
    path: /etc/default/vector
    line: VECTOR_CONFIG_TOML=/etc/vector/*.toml
```
_before_ importing the `vector` role, to avoid starting `vector` with incomplete configuration.

**Comment by davidlukac** [comment]
... and this actually conflicts with
```
- name: Use the right config_file
  lineinfile:
    path: /etc/default/vector
    line: "VECTOR_CONFIG={{ vector_config_file }}"
    state: present
```
from the role :-/
